texto = input('Digite qualquer coisa: ')
print('O tipo primitivo dessa coisa é {}'.format(type(texto)))
print('Esse algo é um número?', texto.isnumeric())
print('Esse algo é alfábetico?', texto.isalpha())
print('Esse algo é alfanumérico?', texto.isalnum())
print('Esse algo está em maiuscula?', texto.isupper())
print('Esse algo está em minuscula?', texto.islower())
print('Esse algo está capitalizada?', texto.istitle())
print('Esse algo contém apenas espaços?', texto.isspace())